arch:
  - amd64
  - ppc64le
  
dist: bionic
language: java
jdk:
  - openjdk14
env:
  - NODE_VERSION="10"
  - NODE_VERSION="14"
install:
  - nvm install "$NODE_VERSION"
  - npm install
script:
  - nvm use "$NODE_VERSION"
  - npm test
