arch:
  - amd64
  - ppc64le
dist: bionic
language: java
jdk:
  - openjdk8
env:
  - NODE_VERSION="10"
  - NODE_VERSION="14.1.0"
jobs:
 exclude:
  - env: NODE_VERSION="10"
    arch: ppc64le
install:
  - nvm install "$NODE_VERSION"
  - npm install
script:
  - nvm use "$NODE_VERSION"
  - npm test
