arch
  - amd64
  - ppc64le

dist: bionic
language: java
jdk:
  - openjdk11

env:
  - NODE_VERSION="10"
    arch: amd64
  - NODE_VERSION="14"
    arch: amd64
  - NODE_VERSION="14"
    arch: ppc64le

install:
  - nvm install "$NODE_VERSION"
  - npm install
script:
  - nvm use "$NODE_VERSION"
  - npm test
